language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: n+7XUFZgxis4hRpPy1Hqxieor0g6jNddz3sy9qNKP51y1RBplPWwoeOaZRPS9Jn90XUeXlQQ84IX+JpZr2K+L4R8CYZmxpmMhIveVc50sZIjA+9xFtcezQwYrSCe2j9EZfpjW/F26sCzfAgnm6CzCPWvAon6W6q4FZm5+7WacS+1Lgmex0qlF/ggG8ivuAGHw9Ur2Gkm2YAqMtCPnEEMC+SGv8J0Jg8Hm90IkUqK1yqXhgeGKW6y9w5RHPVq7K7iAhypcbAnJ083HXKp4ZB73YJob3IQb12OkvQ1iwut6mpTjKLRQCP08jzv+6BGE0X9srUQo5ByZTusfUKk2S+FZKbwT81Wnv4isEjP/FLnTJ6kREbtuhAEJ8oFprBdQfLntqChhSajgTQ5Rd7rDYj1K764rwobM4dTvDd7zRaakExPdhBuGGldSS15jmrGrUsB7WCfeA60IPaWpTN0TepL520Q9OngNweZkEFRQZ/lUHXMB+5xW7wGKTcjuurJbhV1zFNMNAtd55pb2A6fFCS+tNqxrZGrNgMj72JjRRJAoP6iZat3iHzWfWwM9yK92nOKGjKh8llqdbRrPD9IlBO0pHZQmxXsDVG445VCsZdN74vvNwitdkaHu6BDVVHxPFCHhbjO2ldm+tFzDqlLUuSWBBHxfLJLGmhH67UtT30ICwI=
  app: demo-cicd
  on:
    repo: glitchdemos/demo-cicd-github-travis-heroku-mlab
